version: '3.8'

services:
  zeek:
    image: zeek/zeek:latest
    container_name: zeek
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./zeek_logs:/usr/local/zeek/logs
    command: ["zeekctl", "deploy"]

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./suricata_logs:/var/log/suricata
      - ./suricata_rules:/etc/suricata/rules
    command: ["suricata", "-i", "eth0", "-c", "/etc/suricata/suricata.yaml"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  traffic_analyzer:
    image: python:3.10
    container_name: traffic_analyzer
    volumes:
      - ./scripts:/app
    working_dir: /app
    command: ["python", "network_monitor.py"]
    depends_on:
      - zeek
      - suricata
    restart: unless-stopped

volumes:
  elasticsearch_data:
