version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  zeek:
    image: zeek/zeek:latest
    container_name: zeek
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
      - ./zeek_logs:/usr/local/zeek/logs
    command: ["zeekctl", "deploy", "-i", "ens18", "-C"]
    
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
      - ./suricata_logs:/var/log/suricata
      - ./suricata.yaml:/etc/suricata/suricata.yaml
    command: ["-i", "ens18"]

  traffic_analyzer:
    image: python:3.10
    container_name: traffic_analyzer
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "network_monitor.py"]
